# Generated by Django 5.0.7 on 2024-07-28 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_alter_profile_bio_alter_profile_country'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
